from ..assembly import AssemblyProtocol as AssemblyProtocol, toCAF as toCAF, toVTK as toVTK
from itertools import chain as chain

def exportAssembly(assy: AssemblyProtocol, path: str) -> bool: ...
def exportCAF(assy: AssemblyProtocol, path: str) -> bool: ...
def exportVTKJS(assy: AssemblyProtocol, path: str): ...
def exportVRML(assy: AssemblyProtocol, path: str): ...
def exportGLTF(assy: AssemblyProtocol, path: str, binary: bool = ..., tolerance: float = ..., angularTolerance: float = ...): ...
