from ..shapes import Shape as Shape

def exportVTP(shape: Shape, fname: str, tolerance: float = ..., angularTolerance: float = ...): ...
def toString(shape: Shape, tolerance: float = ..., angularTolerance: float = ...) -> str: ...
